data_params:
  data_dir: data
  overlap_height_ratio: 0.0
  overlap_width_ratio: 0.0
  test_dataset_names:
    - Set5
    - Set14
    - BSD100
    - Urban100
  train_dataset_name: DIV2K
exp_params:
  add_discriminator: false
  batch_size: 64
  device: cuda
  epochs: 100
  lr: 0.0001
  num_workers: 4
  patch_size: 48
  scale_factor: 4
log_params:
  log_dir: logs
  result_dir: results
  save_interval: 5
  test_model_path: "logs/run_2/best_model.pth"
model_params:
  depth: 13
  width: 64
